# title:            Sunghyun Kim
description:      Sunghyun Kim's personal site
url:              https://frssp.github.io
signoff:          # Sunghyun Kim
disqus_shortname: frssp-github-io # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         CV
    url:          /index.html
  - name:         Presentation
    url:          /presentation
  - name:         Blog   
    url:          /post   
  - name:         phys_kr
    url:          /phys_kr

#  - name:         GitHub
#url:          http://github.com/frssp
#external:     true
# highlighter:      pygments
plugins:
  - jemoji
# permalink:        pretty
markdown: kramdown
